import os
import time
'''启动程序'''
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\esf.py')
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\chaoyang.py')
time.sleep(30)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\haidian.py')
time.sleep(30)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\docheng.py')
time.sleep(10)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\xicheng.py')
time.sleep(10)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\fengtai.py')
time.sleep(10)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\shijingshan.py')
time.sleep(10)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\tongzhou.py')
time.sleep(10)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\daxing.py')
time.sleep(10)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\changping.py')
time.sleep(10)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\shunyi.py')
time.sleep(10)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\fangshan.py')
time.sleep(10)
os.system(r'python D:\Users\dell\PycharmProjects\PY\lj_data\lj_update.py')
